#!/bin/sh
#
# $ rmspams.sh for OpenBSD,v 1.5 2016/02/05 milo974 Exp $
#
# Copyright (c) 2016 Wesley MOUEDINE ASSABY <milo974@gmail.com>
#
# Permission to use, copy, modify, and distribute this software for any
# purpose with or without fee is hereby granted, provided that the above
# copyright notice and this permission notice appear in all copies.
#
# THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES
# WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF
# MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR
# ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES
# WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN
# ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF
# OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.

_START_DIR="/var/mailserver/mail/"
_END_DIR="/.Spam/cur"
_PF_TABLE="blacksmtp"
_PF_FILE="/etc/blacksmtp"
_WHITE_FILE="/etc/whitesmtp" # We trust
_TMP="${TMPDIR:=/tmp}"
_TMPDIR=$(mktemp -dp ${_TMP} .rmspams-XXXXXXXXXX) || exit 1
_TMP_FILE="$_TMPDIR/rmspams$RANDOM.tmp"

bye_bye() {
        rm -rf ${_TMPDIR}
        exit 1
}

trap "bye_bye" 1 2 3 13 15

usage() {
echo "!!! ${@}"
echo "Usage: ${0##*/} name@domain.ext" >&2
bye_bye
}

whatodo() {
DET=0 # Variable de detection
echo "$i = $SCAN -- Remaining : $NBTMP"
while read MX ; do

	echo $SCAN | grep "$MX$" > /dev/null 2>&1
	if [ "$?" == 0 ]; then
		echo "-- Find domain $MX! Next!"
		DET=1
	fi
done < $_WHITE_FILE

if [ $DET == 0 ]; then
	echo "Add this IP to blacklist ? \c"
	read WHAT < /dev/tty
	if [ "$WHAT" == "q" ]; then
		rm -f /tmp/rmspams* 2> /dev/null
		exit 0
	fi

	if [ "$WHAT" != "y" ] && [ "$WHAT" != "n" ]; then
	echo "Please, answer by 'y'(for yes) or 'n'(for no) and 'q' to quit"
	whatodo
	fi

	if [ "$WHAT" == "y" ]; then
		grep $i $_PF_FILE > /dev/null 2>&1
		if [ "$?" == 1 ]; then
		echo $i >> $_PF_FILE
		/sbin/pfctl -t $_PF_TABLE -T add $i
			else
			echo "Already added."
		fi
	fi
fi
}

clearspams() {
	rm -rf ${_TMPDIR}
	rm -f $FULL_DIR/* 2> /dev/null
	[ "$(find $FULL_DIR -mindepth 1)" ] || echo "The spams has been removed."
	echo "Now, Blacklist contains $(cat $_PF_FILE | wc -l) IP.\n"
	exit 0
}

# TESTS

UID=$(id -u)
if [ "$UID" != 0 ]; then
	usage "This program can run only as root."
fi

/sbin/pfctl -s Tables | grep "$_PF_TABLE" > /dev/null 2>&1

if [ "$?" != 0 ]; then
	usage "The table $_PF_TABLE doesn't exist."
fi

if [ ! -f "$_PF_FILE" ]; then
	usage "The file $_PF_FILE doesn't exist."
fi

if [ ! -f "$_WHITE_FILE" ]; then
	usage "The file $_WHITE_FILE doesn't exist."
fi

if [ "$#" -gt "1" ];then
	usage "Too arguments."
fi 

if [ "$#" == 0 ]; then
	usage "Need an email address."
fi

echo $1 | grep '^[a-zA-Z0-9._%+-]*@[a-zA-Z0-9]*[\.[a-zA-Z0-9-]*]*[a-zA-Z0-9]$' > /dev/null 2>&1
if [ "$?" != 0 ]; then
	usage "Bad recipient."
fi

FULL_DIR=$_START_DIR$(echo $1 | awk -F "@" '{print $2}')"/"$(echo $1 |awk -F "@" '{print $1}')$_END_DIR
NBT=$(/sbin/pfctl -t$_PF_TABLE -Tshow | wc -l)
NBF=$(cat $_PF_FILE | wc -l)


if [ "$NBF" != "$NBT" ]; then
	usage "Inconsistency between TABLE and FILE (PF)!"
fi

if [ -d "$FULL_DIR" ]; then
	echo "The working directory : \c"$FULL_DIR"\n\n"
	else
	usage "The folder $FULL_DIR doesn't exist!"
fi


[ "$(find $FULL_DIR -mindepth 1)" ] || usage "No spams!"

# START

echo "Before, Blacklist contains $NBT IP.\n"

touch $_TMP_FILE
touch $_TMP_FILE.list

for f in $FULL_DIR/* ; do
	grep "^Received: from" $f| perl -lne 'print $& if /(\d+\.){3}\d+/' | xargs -I IP echo IP | grep -vE '(^127\.0\.0\.1)|(^192\.168)|(^10\.)|(^172\.1[6-9])|(^172\.2[0-9])|(^172\.3[0-1])' >> $_TMP_FILE
done

cat $_TMP_FILE | sort | uniq > $_TMP_FILE.list
NBTMP=$(cat $_TMP_FILE.list | wc -l)
echo "Total IP found : $NBTMP\n"

while read i; do
	SCAN=$(nslookup -query=a $i | \
	grep -v canonical | grep name | awk '{print $4}')

	if [ -z "$SCAN" ]; then
		NBTMP=$(expr $NBTMP - 1)
		SCAN="unknown."
		echo "-- $SCAN!" 
	fi 

	if [ "$SCAN" != "localhost." ] && [ "$SCAN" != "unknown." ]; then
		NBTMP=$(expr $NBTMP - 1)
		whatodo
	fi

done < $_TMP_FILE.list

clearspams
